services:
  todo_server:
    build: ./Todo_Server
    container_name: todo_server_dev
    ports:
      - "5005:5005"
    environment:
      - MONGO_URI=mongodb://db:27017/todoapp
      - JWT_SECRET=supersecret
      - PORT=5005
      - NODE_ENV=development
    volumes:
      - ./Todo_Server:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - appnet
    command: nodemon src/server.js

  todo_client:
    build:
      context: ./Todo_Client
      dockerfile: Dockerfile.dev
    container_name: todo_client_dev
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:5005/api
    volumes:
      - ./Todo_Client:/app
      - /app/node_modules
    depends_on:
      - todo_server
    networks:
      - appnet

  db:
    image: mongo:5
    container_name: todo_db_dev
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_data_dev:/data/db
    networks:
      - appnet

volumes:
  db_data_dev:

networks:
  appnet:
